[package]
name = "rust_mod_player"
version = "0.1.0"
authors = ["Philipp Schwarz <schwarz_philipp@hotmail.de>"]
license = "EUPL-1.2"

[dependencies]
hound = "3.4.0"

[lib]
name = "rust_mod"
path = "src/lib.rs"